#!/usr/bin/env python3
"""Turn the crawled poopicker site mirror into an Arduino PROGMEM header.

Matches the pattern PS5-Server-Pico already uses for its own blobs: each file is
gzipped, stored once in PROGMEM, and served with `Content-Encoding: gzip` so the
console browser inflates it. That keeps the flash image small and, just as
importantly, cuts the bytes on the wire - the chains are timing sensitive and
every KB over the air is latency inside a race.

Identical files are stored once: rop.js / syscalls.js repeat across the retail,
devkit and relapse mirrors.

    python3 tools/mkpages.py sites ../PS5-Server-Pico/PS5_Server_Pico/payloads.h
"""

import os
import sys
import gzip
import hashlib
import io


def gz(data: bytes) -> bytes:
    """Deterministic gzip - mtime pinned to 0 so rebuilds are byte-identical."""
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as f:
        f.write(data)
    return buf.getvalue()


def emit_array(f, name, data, comment):
    f.write(f"/* {comment} */\n")
    f.write(f"static const uint8_t {name}[] PROGMEM = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        f.write("    " + "".join(f"0x{b:02x}," for b in chunk) + "\n")
    f.write("};\n\n")


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        return 2
    root, out_h = sys.argv[1], sys.argv[2]

    entries = []            # (key, blob_name, raw_len, gz_len)
    blobs = {}              # blob_name -> gzipped bytes
    order = []

    for dirpath, _dirs, files in os.walk(root):
        for fn in sorted(files):
            full = os.path.join(dirpath, fn)
            key = os.path.relpath(full, root).replace(os.sep, "/").lower()
            with open(full, "rb") as fh:
                raw = fh.read()
            comp = gz(raw)
            h = hashlib.sha256(comp).hexdigest()
            name = f"b_{h[:10]}"
            if name not in blobs:
                blobs[name] = comp
                order.append(name)
            entries.append((key, name, len(raw), len(comp)))

    entries.sort(key=lambda e: e[0])

    os.makedirs(os.path.dirname(out_h) or ".", exist_ok=True)
    with open(out_h, "w") as f:
        f.write("/* Generated by tools/mkpages.py - do not edit by hand.\n")
        f.write(f" * {len(entries)} paths, {len(order)} unique blobs.\n")
        f.write(" * Source mirror: poopicker/embedded/sites (fetch_sites.py).\n")
        f.write(" */\n")
        f.write("#ifndef PAYLOADS_H\n#define PAYLOADS_H\n\n")
        f.write("#include <Arduino.h>\n#include <pgmspace.h>\n\n")

        for name in order:
            emit_array(f, name, blobs[name], f"{len(blobs[name]):,} B gzipped")

        f.write("struct web_file {\n"
                "    const char    *key;    /* host + url path, lowercase */\n"
                "    const uint8_t *data;   /* gzipped */\n"
                "    uint16_t       gz_len;\n"
                "    uint32_t       raw_len;\n"
                "};\n\n")

        f.write("static const web_file g_files[] = {\n")
        for key, name, rawlen, gzlen in entries:
            k = key.replace("\\", "\\\\").replace('"', '\\"')
            f.write(f'    {{ "{k}", {name}, {gzlen}u, {rawlen}u }},\n')
        f.write("};\n\n")
        f.write(f"#define WEB_FILE_COUNT {len(entries)}\n")
        f.write("\n#endif /* PAYLOADS_H */\n")

    total_raw = sum(e[2] for e in entries)
    total_gz = sum(len(b) for b in blobs.values())
    print(f"{len(entries)} paths -> {out_h}")
    print(f"  unique blobs : {len(order)}")
    print(f"  raw bytes    : {total_raw:,}")
    print(f"  gzipped      : {total_gz:,}  "
          f"({100.0 * total_gz / max(1, total_raw):.0f}%)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
